name: Test
on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        type: string
jobs:
  test:
    runs-on: Ubuntu-24.04
    steps:
    - run: |
        for i in {1..10}; do
          time curl -v $URL
        done
      env:
        URL: ${{ inputs.url }}
